#src/Aldor/InftechBundle/Resources/config/doctrine/Post.orm.yml
Studia\XerksesBundle\Entity\Employee:
    type: entity
    repositoryClass: Studia\XerksesBundle\Repository\EmployeeRepository
    table: employee
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        xero:
            targetEntity: Xero
            inversedBy: employees
            joinColumn:
                name: xeroid
                referencedColumnName: id

