Studia\XerksesBundle\Entity\Opinion:
    type: entity
    repositoryClass: Studia\XerksesBundle\Repository\OpinionRepository
    table: opinion
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        rating:
            type: integer
        attention:
            type: text
        date:
            type: datetime
    manyToOne:
        users:
            targetEntity: User
            inversedBy: opinions
            joinColumn:
                name: userid
                referencedColumnName: id
            inverseJoinColumns:
                name: opinionid
                referencedColumnName: id
        xeros:
            targetEntity: Xero
            inversedBy: opinions
            joinColumn:
                name: xeroid
                referencedColumnName: id
            inverseJoinColumns:
                name: opinionid
                referencedColumnName: id

