Studia\XerksesBundle\Entity\Prices:
    type: entity
    repositoryClass: Studia\XerksesBundle\Repository\PricesRepository
    table: prices
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        pricevalue:
            type: float
    oneToOne:
        typofservice:
            targetEntity: ServiceTyp
            inversedBy: prices
            joinColumn:
                name: servicetypid
                referencedColumnName: id
    manyToOne:
        xero:
            targetEntity: Xero
            inversedBy: prices
            joinColumn:
                name: xeroid
                referencedColumnName: id

