<?php

namespace Studia\XerksesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentInRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentInRepository extends EntityRepository
{
}
