<?php

namespace Studia\XerksesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PaymentOutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentOutRepository extends EntityRepository
{
}
