<?php

namespace Studia\XerksesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * XeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XeroRepository extends EntityRepository
{
}
